default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  port: 5432
  username: postgres
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tunecore-challenge_development

test:
  <<: *default
  database: tunecore-challenge_test

production:
  <<: *default
  database: tunecore-challenge_production
  username: tunecore-challenge
  password: <%= ENV['TUNECORE-CHALLENGE_DATABASE_PASSWORD'] %>
